name: Cow BFF (validate)

concurrency: staging_environment

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  # unit-tests:
  #   name: "Unit tests"
  #   environment: Staging
  #   runs-on: ubuntu-latest
  #   env:
  #     DATABRICKS_CLUSTER_ID: ${{ vars.DATABRICKS_CLUSTER_ID }}
  #     DATABRICKS_HOST: ${{ vars.DATABRICKS_HOST }}
  #     DATABRICKS_TOKEN: ${{ vars.DATABRICKS_TOKEN }}

  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"
  #         cache: "pip"
  #     - run: pip install -r requirements.txt
  #     - name: Run unit tests
  #       run: pytest -s -v tests/ --disable-warnings

  deploy:
    name: "Deploy bundle and run notebook"
    environment: Staging
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - shell: bash
        name: Deploy to QA environment
        run: databricks bundle deploy -t qa
