name: Cow BFF (validate)

concurrency: staging_environment

on:
  workflow_dispatch:

  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main

jobs:
  test-pipeline:
    name: "QA"
    environment: Staging
    runs-on: ubuntu-latest
    env:
      DATABRICKS_CLUSTER_ID: ${{ secrets.DATABRICKS_CLUSTER_ID }}
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      #----------------------------------------------
      #       check-out repo and set-up python + env
      #----------------------------------------------
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - run: pip install -r requirements.txt
      #----------------------------------------------
      #              run test suite
      #----------------------------------------------
      - name: Run unit tests
        run: pytest -s -v tests/ --disable-warnings
      - name: "Prepare branch"
        uses: actions/checkout@v3
      - name: "Set up CLI"
        uses: databricks/setup-cli@main
      #----------------------------------------------
      #              deploy bundle to Staging
      #----------------------------------------------
      - name: "Deploy bundle"
        run: databricks bundle deploy
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: qa
      #----------------------------------------------
      #              run integration tests
      #----------------------------------------------
      - name: "Run deployment"
        run: databricks bundle run
        env:
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
          DATABRICKS_BUNDLE_ENV: qa
